
package org.oasis_open.docs.wsrf.rw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-06-10T15:01:26.637-07:00
 * Generated source version: 3.1.10
 */

public class ResourceUnknownFault extends Exception {
}
